lmmap <- (lm(map ~ mapWC, data = meta))
lmmat <- lm(mat ~ matWC, data = meta)
windows(12, 8)
par(mfrow=c(1, 2))
plot(meta$map ~ meta$mapWC, pch = 19, ylab = "MAP (mm/y)", xlab = "MAP_WC (mm/y)")
abline(lmmap)
legend('topleft', legend = paste0('R2 = ', round(summary(lmmap)$r.squared, 2)), bty = 'n')
plot(meta$mat ~ meta$matWC, pch = 19, ylab = 'MAT (C)', xlab = 'MAT_WC (C)')
abline(lmmat)
legend('topleft', legend = paste0('R2 = ', round(summary(lmmat)$r.squared, 2)), bty = 'n')
rm(lmmap, lmmat)